<?php

require_once dirname(__FILE__) . '/../../../application/models/Certificate.php';

/**
 * Test class for Application_Model_Certificate.
 * Generated by PHPUnit on 2012-01-29 at 16:44:25.
 */
class Application_Model_CertificateTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Application_Model_Certificate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Application_Model_Certificate;
        $this->object->setId(2)
            ->setPlayerId(5)
            ->setDate('2012-10-11 15:15:15')
            ->setEndDate('2012-10-18 15:15:15');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Application_Model_Certificate::setId
     */
    public function testSetId() {
        $return = $this->object->setId(5);
        $this->assertInstanceOf('Application_Model_Certificate', $return);
    }

    /**
     * @covers Application_Model_Certificate::getId
     */
    public function testGetId() {
        $return = $this->object->getId();
        $this->assertEquals(2, $return);
    }

    /**
     * @covers Application_Model_Certificate::setPlayerId
     */
    public function testSetPlayerId() {
        $return = $this->object->setId(67);
        $this->assertInstanceOf('Application_Model_Certificate', $return);
    }

    /**
     * @covers Application_Model_Certificate::getPlayerId
     */
    public function testGetPlayerId() {
        $return = $this->object->getPlayerId();
        $this->assertEquals(5, $return);
    }

    /**
     * @covers Application_Model_Certificate::setDate
     */
    public function testSetDate() {
        $return = $this->object->setDate('2012-10-11 15:15:15');
        $this->assertInstanceOf('Application_Model_Certificate', $return);
        $return = $this->object->setDate(new DateTime);
        $this->assertInstanceOf('Application_Model_Certificate', $return);
        $this->setExpectedException('InvalidArgumentException');
        $this->object->setDate(array());
    }

    /**
     * @covers Application_Model_Certificate::getDate
     */
    public function testGetDate() {
        $return = $this->object->getDate();
        $this->assertInstanceOf('DateTime', $return);
    }
    
    /**
     * @covers Application_Model_Certificate::setDate
     */
    public function testSetEndDate() {
        $return = $this->object->setEndDate('2012-10-11 15:15:15');
        $this->assertInstanceOf('Application_Model_Certificate', $return);
        $return = $this->object->setEndDate(new DateTime);
        $this->assertInstanceOf('Application_Model_Certificate', $return);
        $this->setExpectedException('InvalidArgumentException');
        $this->object->setEndDate(array());
    }

    /**
     * @covers Application_Model_Certificate::getDate
     */
    public function testGetEndDate() {
        $return = $this->object->getEndDate();
        $this->assertInstanceOf('DateTime', $return);
    }

}

?>
