<p class="wrappertext"><br />
<?php echo $this->cert->player; ?> heeft een certificaat gehaald op 1 wereld(en):
<table class="wrappertable">
<br>
<tr>
<th>Rang</th>
<th>Naam</th>
<th>Stam</th>
<th>Punten</th>
<th>Dorpen</th>
<th>Punten gemiddelde</th>
<th>Server</th>
<th>Start van Certificaat</th>
<th>Einde van Certificaat</th>
</tr>
<tr>
<td>1</td>
<td><?php echo $this->cert->player; ?></td>
<td><em>geen stam</em></td>
<td>256</td>
<td>1</td>
<td>256</td>
<td>NL26</td>
<td><?php echo $this->cert->date; ?></td>
<td><?php echo $this->cert->endDate; ?></td>
</tr>
</table>
<br />
<strong class="wrappertext"><a href="/">Ga terug naar de website</a></strong><br />
<br />
<img class="center" src="/images/pal_sword.png" alt="gefeliciteerd! je hebt je certificaat"/>
</p>