<!DOCTYPE html>
<html lang="nl"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <?php echo $this->headTitle() ?>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="/style.css">
</head>
  <body><div class="content">
      <?php echo $this->layout()->content; ?>
    <footer>
      <em>Tribal Wars</em> en <em>InnoGames</em> vallen onder copyright van InnoGames GmbH.
    </footer>
    </div>
  

</body></html>
