  <span class="subtitle">Alternatieven</span>

  <p>Onderstaande alternatieven werden reeds aangekondigd door verschillende spelers op het <em>Algemeen Forum</em>. We bessefen dat de spelers die deze ide&euml;en steunen ook willen strijden voor het behoud van plezier op <em>Tribal Wars</em>. Echter willen we ons niet associ&euml;ren met aggressieve en afbrekende acties. Daarom hebben we hier een omschrijving neergeplaatst die uitlegt waar volgens ons de acties tekort schieten.</p>

  <p>We willen benadrukken dat wij dezelfde streefdoelen hebben als deze actievoerders en nodigen hen alvast uit voor een gesprek zodat we de bestaande ide&euml;en kunnen gaan samenvoegen om tot een gezamelijke oplossing te komen waarin iedereen voordeel heeft. Laat dus gerust van je horen wanneer je denkt dat een samenwerking tot een beter resultaat kan leiden.</p>

  <ul>
    <li><a href="#chap0">Boycot</a></li>
    <li><a href="#chap1">Massastam</a></li>
    <li><a href="#chap2">Massaal klagen tegen Community Managers en Innogames</a></li>
  </ul>

<article>
  <h2><a id="chap0"></a>Boycot</h2>

  <p>Een van de voorstellen die momenteel op het algemeen forum een grote aanhang heeft is de boycot van nieuwe werelden waarop de beruchte <em>Premium</em>-faciliteiten worden ingeschakeld. Strikt gezien houdt dit in dat deze groep spelers geen account zullen aanmaken op die werelden, met als doel <em>InnoGames</em> een signaal te geven dat hun nieuwe beleid onverantwoord is.</p>

  <p>Hoewel het doel van deze actie vrij aannemelijk is, is het middel echter niet effectief: Het aantal aanhangers op het forum is slechts een heel gering groepje spelers. Daarnaast zijn er ook mensen die heel graag willen spelen op de nieuwe wereld en dit dus ook gewoon zullen doen. <em>InnoGames</em> zal sowieso niet wakkerliggen van een paar spelers die niet akkoord gaan, terwijl duizenden anderen gewoon blijven spelen. Het enige wat je dus bereikt is dat je zelf niet speelt, wat evengoed een beslissing had kunnen zijn omwille van je drukke leven of de vele andere accounts die je moet onderhouden.</p>

  <p>Met de <strong>NPO-beweging</strong> willen we het via een andere weg aanpakken: We gunnen <em>InnoGames</em> gerust hun kans om meer geld binnen te halen, maar we willen elke speler gaan sensibiliseren zodat die inzien dat geld geen middel dient te zijn om het spel te spelen (zoals <em>InnoGames</em> het ook zelf verkondigd). Daarnaast willen we ook degene die dit standpunt verdedigen belonen door een systeem in te voeren waarop zij een meerwaarde krijgen ten opzichte van wie liever betaalt voor zijn rang. Onze acties bevatten dus in geen geval destructieve methodes, in tegendeel. Net daarom verwachten we ook dat de community er sterker door wordt in plaats van onderlinge problemen tussen moderatoren, community managers en spelers te veroorzaken. Dit laatste maakt het spel zeker niet aangenamer.</p>
</article>

<article>
  <h2><a id="chap1"></a>Massastam</h2>

  <p>Leuk idee, maar zelfs de grootste massastammen die ik ooit heb meegemaakt hebben nooit 60% van de wereld in beslag kunnen nemen. Dit zou betekenen dat je ongeveer 60% van de spelers kan overtuigen om doelloos te spelen op de wereld, want gemiddeld 60% van hun omgeving zal omringd zijn door stamgenoten, de ze dus niet kunnen farmen en/of overnemen. We kunnen moeilijk geloven dat er zoveel mensen dit idee zullen steunen.</p>

  <p>Met de <strong>NPO-beweging</strong> is ons doel niet om het spelen doelloos te maken, maar net om het originele doel van het spel in stand te houden: tactiek, strategie en vooral skills. Wij willen niet dat minder mensen deelnemen aan de nieuwe werelden. We willen net dat de mensen bewijzen dat het kopen van je rang zinloos en waardeloos is.</p>
</article>

<article>
  <h2><a id="chap2"></a>Massaal klagen tegen Community Managers of Innogames</h2>

  <p><em>InnoGames</em> zal hoe dan ook volhouden dat ze meer geld nodig hebben. Een bedrijf heeft namelijk nooit geld genoeg, dus je standpunt gaan verdedigen heeft sowieso geen zin. Uit de andere alternatieven kan je ook afleiden dat er steeds spelers zullen zijn die zich hier niets van aantrekken en gewoon blijven spelen, dus <em>InnoGames</em> zal een paar tiental klachten gewoon vriendelijk afwimpelen</p>

  <p><em>Community Managers</em> hebben in dit dialoog een lastige taak. Zij moeten in naam van <em>InnoGames</em> spreken en mogen daar amper hun eigen mening in verwerken (die is zelfs van geen belang). Evenals spelers kunnen zij ook niet zomaar <em>InnoGames</em> gaan overtuigen dat de beslissing verkeerd is omwille van een paar tientallen klachten. We vinden het al een goeie zaak dat de <em>Community Managers</em> ons toelaat om onze mening uit te drukken (tot op een beschaafde grens uiteraard). Het enige wat zij kunnen doen is die mening doorspelen naar <em>InnoGames</em>, wat uiteindelijk zelfs niet nodig blijkt, gezien er ook mensen van het bedrijf het Algemeen Forum bekijken.</p>

  <p>Het argument dat de <em>Community Managers</em> hun zakken vullen is al helemaal absurd. <em>InnoGames</em> zal heus niet meer omzet willen draaien om hun werkvolk een ferme opslag te kunnen geven. De eerste werkgever die dit als doel voorop stelt moet nog geboren worden.</p>

  <p>Met de <strong>NPO-beweging</strong> willen we ons dus niet verzetten tegen onze <em>Community Managers</em> rechtstreeks en <em>Innogames</em> onrechtstreeks, maar aantonen dat we het probleem op een creatieve manier uit de weg kunnen helpen. Op die manier kunnen we nog steeds naast elkaar leven en gesprek voeren, want wanneer men valse beschuldigingen begint te gooien of mensen gaat verwijten, dan bereik je dit alvast niet.</p>
</article>
